### ISSUE TITLE
OptionalProperty

### ISSUE THREAD

**Issue by jrocha** [grammophone/Grammophone.Serialization#2]
I think it is quite annoying that we can't add an OptionalProperty to a property with auto-generated backing field to an existing class and have a serialized stream deserialing on that new version of the class. 

I was wondering if we could add an OptionalProperty attribute and during deserialization process we could validate k__BackingField fields over this attribute and continue deseralization without throwing an error.

What do you think about that?

**Comment by grammophone** [comment]
Hello,

Thank you for your comment. If in your scenario the `OptionalFieldAttribute` doesn't work with the standard formatters*, i think it is best to keep the behavior complying with the standard. Instead, 
there is the option to use a [ISerializationSurrogate](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.iserializationsurrogate(v=vs.110).aspx) in order to take special care of the class.

__

\* For the standard `BinaryFormatter`, the documentation doesn't mention it but it has been found that when the `AssemblyFormat` is `FormatterAssemblyStyle.Simple`, [the formatter treats everything as optional](https://stackoverflow.com/questions/18579431/does-the-optionalfieldattribute-actually-work). Maybe a setting could be added to emulate this undocumented behavior of `BinaryFormatter`.
